### ISSUE TITLE
这个项目有人维护吗？  签名算法要自己写?

### ISSUE THREAD

**Issue by icehong** [tencentyun/cos_android_sdk#2]

**Comment by bradyxiao** [comment]
@icehong 
/**
 因签名需要获取 secretKey 和 secretId, 所以终端未提供获取签名的方法，
可以搭建一个签名服务器，获取签名；
该类描述了如何计算签名
*/
import android.text.TextUtils;
import android.util.Base64;

import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Random;

import javax.crypto.Mac;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;

/**
 * Created by bradyxiao on 2016/8/4.
 * Sign 工具类
 */
public class SignUtils {

    private String mAPPID = null;
    private String mBucket = null;
    private String mFileID = null;
    private long mExpiredTime = 0;
    private long mCurrentTime = 0;
    private String mScrectKey = null;
    private String mScrectID = null;


    /**
     public SignUtils(String mAPPID, String mBucket, String mFileID, long mExpiredTime){
     //其中 nFileId 的格式签名 带“/”
     this.mAPPID = mAPPID;
     this.mBucket = mBucket;
     this.mFileID = mFileID;
     this.mExpiredTime = mExpiredTime;
     }
     */
    public SignUtils(String mAPPID, String mBucket, String mScrectID, String mScrectKey, String mFileID, long mExpiredTime){
        //其中 nFileId 的格式签名 带“/”，如 /mydir/1.txt
        this.mAPPID = mAPPID;
        this.mBucket = mBucket;
        this.mFileID = mFileID;
        this.mExpiredTime = mExpiredTime;
        this.mScrectID = mScrectID;
        this.mScrectKey = mScrectKey;
    }

    public SignUtils(){}

    public String getSignForUser(){
        String sign = null;
        String signUrl = getSignUrl();
        sign = getSign(signUrl,this.mScrectKey);
        sign = sign.replaceAll("\n","");
        return  sign;
    }

    private String getSignUrl(){
        String signUrl = null;
        /**
         * 形如：1) a=[appid]&b=[bucket]&k=[SecretID]&e=[expiredTime]&t=[currentTime]&r=[rand]&f=；
         *       2) a=[appid]&b=[bucket]&k=[SecretID]&e=[expiredTime]&t=[currentTime]&r=[rand]&f=[fileid]；
         *       3) 其中检测签名时与各个字段的排序顺序无关；
         *
         * 签名类型：
         *        1）下载（不开启token防盗链）	不验证签名
         *        2） 上传	多次有效签名
                  3）查询目录、文件	多次有效签名
                  4）创建目录	多次有效签名
                  5）下载（开启token防盗链）	多次有效签名
                 6）删除目录、文件	单次有效签名
                 7）更新目录、文件	单次有效签名
         */

        StringBuilder stringBuilder = new StringBuilder();
        stringBuilder.append("a=" + mAPPID);
        stringBuilder.append("&b=" + mBucket);
        stringBuilder.append("&k=" + mScrectID);

        long random = Math.abs(new Random().nextLong());
        stringBuilder.append("&r=" + random);
        if(mFileID == null){
            mCurrentTime = System.currentTimeMillis()/1000;
            mExpiredTime = mExpiredTime*24*3600 + mCurrentTime;
            stringBuilder.append("&e=" + mExpiredTime);
            stringBuilder.append("&t=" + mCurrentTime);
            stringBuilder.append("&f=");
        }else{
            try {
                mCurrentTime = System.currentTimeMillis()/1000;
                mExpiredTime = 0;
                stringBuilder.append("&e=" + mExpiredTime);
                stringBuilder.append("&t=" + mCurrentTime);
                //针对fileid 进行编码；
                //格式为： /appid/bucket/fileid;
                mFileID = "/"+ mAPPID + "/" +mBucket +mFileID;
                mFileID = urlEncoder(mFileID);
                stringBuilder.append("&f="+mFileID);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        signUrl = stringBuilder.toString();
        return signUrl;
    }

    /**
     * HAMCSHA1签名
     */

    private byte[] getHmacSha1(String signUrl, String scretKey){
        byte[] hmacSha1 = null;
        try {
            byte[] byteKey = scretKey.getBytes("utf-8");
            SecretKey hmacKey = new SecretKeySpec(byteKey, "HmacSHA1");
            Mac mac = Mac.getInstance("HmacSHA1");
            mac.init(hmacKey);
            hmacSha1 = mac.doFinal(signUrl.getBytes("utf-8"));
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        } catch (NoSuchAlgorithmException e) {
            e.printStackTrace();
        } catch (InvalidKeyException e) {
            e.printStackTrace();
        }
        return hmacSha1;
    }

    /**
     * join byte
     */
    private byte[] joiner(byte[] hmacSHA1, byte[] signUrlToByte ){
        int len1 = hmacSHA1.length;
        int len2 = signUrlToByte.length;
        byte[] allByte = new byte[len1 + len2];
        for(int i = 0; i< len1; i++){
            allByte[i] = hmacSHA1[i];
        }
        for(int i = 0; i< len2; i ++){
            allByte[len1+i] = signUrlToByte[i];
        }
        return allByte;
    }

    /**
     *对fileID进行URLEncoder编码
     */
    private String  urlEncoder(String fileID){
        if(fileID == null){
            return fileID;
        }
        StringBuilder stringBuilder = new StringBuilder();
        String[] strFiled = fileID.trim().split("/");
        int length = strFiled.length;
        for(int i = 0; i< length; i++){
            if("".equals(strFiled[i]))continue;
            stringBuilder.append("/");
            try{
                String str = URLEncoder.encode(strFiled[i], "utf-8").replace("+","%20");
                stringBuilder.append(str);
            }catch (Exception e){
                e.printStackTrace();
            }
        }
        if(fileID.endsWith("/")) stringBuilder.append("/");
        fileID = stringBuilder.toString();
        return fileID;
    }

    /**
     *
     * @param signUrl
     * @param ScrectKey
     * @return
     */
    private String  getSign(String signUrl, String ScrectKey){
        String sign = null;
        try {
            byte[] hmacSha1 = getHmacSha1(signUrl, ScrectKey);
            byte[] all = joiner(hmacSha1, signUrl.getBytes("utf-8"));
            sign = Base64.encodeToString(all,Base64.DEFAULT);
        }catch (Exception e){
            e.printStackTrace();
        }
        return sign;
    }
}

**Comment by icehong** [comment]
为啥不把这个类也放在demo 项目里面呢

而且你们给的这个qclouddemo的包，  直接用 androidstudio 2.3 也打不开， 错误如下

*E:\workspace\qclouddemo\build.gradle*
Error:(1, 0) Plugin with id 'com.android.application' not found.
<a href="openFile:E:\workspace\qclouddemo\build.gradle">Open File</a>

2017-04-17 16:18 GMT+08:00 bradyxiao <notifications@github.com>:

**Comment by dale311** [comment]
这个是个eclipse的项目，仅相当于android studio里面的一个module.需要在build.gradle里面加上

```
buildscript {

    repositories {
        mavenCentral() // or jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'//你自己的gradle版本
    }
}
```

**Comment by scientificRat** [comment]
上面给的这个签名算法和官网cos api文档 描述不一致啊https://www.qcloud.com/document/product/436/7778
反而和优图API 文档描述是一致的 https://www.qcloud.com/document/product/275/3805
到底怎么回事呀，求解答

**Comment by bradyxiao** [comment]
@scientificRat 
https://www.qcloud.com/document/product/436/7778 ==>这个是xml签名算法，即V5版本的
而这个sdk 是json api ，即V4 版本
参看如下：https://cloud.tencent.com/document/product/436/6054
