### ISSUE TITLE
腾讯云到底能不能用啊？请回答下，不行我得赶快说了换，项目急啊！

### ISSUE THREAD

**Issue by q315179743** [tencentyun/cos_android_sdk#5]
按照你们的文档跟demo，上传文件，一直报错：
{
	"code": -5964,
	"message": "ERROR_CGI_PARAM_NO_SUCH_OP",
	"request_id": "NTk1OGIwZDFfY2RhMzNiXzQ2YzhfODc4ODM5"
}
没有操作方法？

---requset里面---
POST /files/v2/1****3/****/****/ HTTP/1.1
Authorization: (----xxx---注释--按#2给出的算法计算的)
==
Connection: Keep-Alive
Accept: */*
User-Agent: cos-android-sdk-v4.1.4.3.6
Content-Type: multipart/form-data; boundary=50e88436-234b-4f52-a627-1b371f30218e
Content-Length: 87492
Host: gz.file.myqcloud.com
Accept-Encoding: gzip

--50e88436-234b-4f52-a627-1b371f30218e
Content-Disposition: form-data; name="op"
Content-Length: 6

upload
--50e88436-234b-4f52-a627-1b371f30218e
Content-Disposition: form-data; name="sha"
Content-Length: 40

----xxx---注释--
--50e88436-234b-4f52-a627-1b371f30218e
Content-Disposition: form-data; name="insertOnly"
Content-Length: 1

1
--50e88436-234b-4f52-a627-1b371f30218e
Content-Disposition: form-data; name="filecontent"
Content-Type: text/plain
Content-Length: 86930

 (----xxx---注释--文件内容)

**Comment by bradyxiao** [comment]
上传文件时， cosPath 不能以 "/" 结束
